### ISSUE TITLE
Firefox Error

### ISSUE THREAD

**Issue by Francis0121** [Nornenjs/nornenjs.system#13]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Received unparsable message: TypeError: Object 2probe has no method 'readUInt8'
    at /home/pi/git/vrcs/web/vrcs/node_modules/binaryjs/lib/client.js:100:37
    at process._tickCallback (node.js:419:13)
```

**Comment by Francis0121** [comment]
``` javascript
var BinaryServer = require('binaryjs').BinaryServer; // BinaryJs (Byte stream)
var bs = BinaryServer({server : server}); // Start BinaryJs server
```

module을 불러오는 것 부터 에러 발생.

**Comment by Francis0121** [comment]
Connection Refused 를 해결한뒤 문제 없이 실행됨

![image](https://cloud.githubusercontent.com/assets/3794501/5575220/c19dc7c8-9017-11e4-95fd-f0ae427a7c66.png)
