### ISSUE TITLE
Connection 의 끊기는 경우 에러 발생.

### ISSUE THREAD

**Issue by Francis0121** [Nornenjs/nornenjs.system#7]
<h3>Client is not yet connected or has closed<h3>
![image](https://cloud.githubusercontent.com/assets/3794501/5341959/a260fb36-7f3d-11e4-9e5c-2f7f0e743d14.png)

언제 발생하는건지 잘모르겠음.

**Comment by Francis0121** [comment]
<b>connection 이 종료될 경우 close </b>

``` javascript
client.on('close', function(stream, meta){
    clearInterval(volumeInterval);
});
```

**Comment by Francis0121** [comment]
<b>위의 상황 뿐아니라 많은 상황에서 Exception 발생</b>

**Comment by Francis0121** [comment]
![image](https://cloud.githubusercontent.com/assets/3794501/5556819/e056b9de-8d2b-11e4-9423-bb98e26b2e0f.png)

에러 하나더 추가

```
/home/pi/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true)
                 ^
TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (/home/pi/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222:18)
    at Receiver.opcodes.1.finish (/home/pi/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:394:12)
    at Receiver.<anonymous> (/home/pi/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/home/pi/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/home/pi/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at Socket.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
```

``` javascript
var socket = io.connect('http://112.108.40.165:3000', { reconnection : false }); // Socket.io
```

add
<b>reconnection : false </b>

**Comment by Francis0121** [comment]
``` html
<head>
<script src='http://112.108.40.165:3000/socket.io/socket.io.js'></script>
</head>
```

반드시 절대경로로 작성해주어야만 실행이됨.

이유 ? 모름

**Comment by Francis0121** [comment]
정상종료가 되지 않을시 위의 error 가 동일하게 발생되어진다.

**Comment by Francis0121** [comment]
<h3>가장위의 'Client is not yet connected or has closed' Error</h3>

<b>Client 가 존재할 경우</b>

```
  _socket: 
   { _socket: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        onend: null,
        destroyed: false,
        bytesRead: 713,
        _bytesDispatched: 1454630,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1419656260321,
        _monotonicStartTime: 55802283,
        parser: null,
        ondata: null,
        _paused: false,
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function],
        read: [Function],
        _consuming: true },
     bytesReceived: 96,
     readyState: 1,
     supports: { binary: true },
     protocol: undefined,
     protocolVersion: 13,
     upgradeReq: 
      { _readableState: [Object],
        readable: true,
        domain: null,
        _events: {},
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '/',
        method: 'GET',
        statusCode: null,
        client: [Object],
        _consuming: false,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: true,
        parser: null },
     _isServer: true,
     _receiver: 
      { fragmentedBufferPool: [Object],
        unfragmentedBufferPool: [Object],
        state: [Object],
        overflow: [],
        headerBuffer: <Buffer 00 c1 e9 af 58 67 bd 09 5c 11>,
        expectOffset: 0,
        expectBuffer: <Buffer 00 c1>,
        expectHandler: [Function],
        currentMessage: [],
        dead: false,
        onerror: [Function],
        ontext: [Function],
        onbinary: [Function],
        onclose: [Function],
        onping: [Function],
        onpong: [Function] },
     _sender: { _socket: [Object], firstFragment: true, _events: [Object] },
     _events: 
      { close: [Object],
        open: [Function],
        drain: [Function],
        error: [Function],
        message: [Object] },
     binaryType: 'arraybuffer' },
```

<b>Client 가 존재하지 않는 경우</b>

```
_socket: 
   { _socket: null,
     bytesReceived: 152,
     readyState: 3,
     supports: { binary: true },
     protocol: undefined,
     protocolVersion: 13,
     upgradeReq: 
      { _readableState: [Object],
        readable: true,
        domain: null,
        _events: {},
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '/',
        method: 'GET',
        statusCode: null,
        client: [Object],
        _consuming: false,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: true,
        parser: null },
     _isServer: true,
     _receiver: null,
     _sender: null,
     _events: { error: [Function] },
     binaryType: 'arraybuffer',
     _closeCode: 1001,
     _closeMessage: '' },
```

<b>Client Javascript Error Handler</b>

``` javascript
try {
                    if(client._socket._socket == undefined){
                        console.log('INFO: Client already disconnected');
                        return;
                    }
                    client.send(jpeg_img);
                }catch(err){
                    console.log(err);
                }
```

**Comment by Francis0121** [comment]
client.js 에서 받아오는 Buffer를 출력해봄 
정상적으로 출력이 되었을 때

```
INFO[client.js]: -  <Buffer 93 01 c0 00>
byte stream connect attempt 0
INFO[client.js]: -  <Buffer 93 02 da 00 24 00 00 80 3f 00 00 80 3f 00 00 00 00 00 00 00 00 00 00 80 3f 00 00 40 40 00 00 00 00 00 00 00 00 00 00 00 00 00>
INFO[client.js]: -  <Buffer 93 05 c0 00>
INFO[client.js]: -  <Buffer 93 01 c0 02>
byte stream connect attempt 0
INFO[client.js]: -  <Buffer 93 02 da 00 24 00 00 00 40 00 00 80 3f 00 00 c8 42 00 00 00 00 00 00 80 3f 00 00 40 40 00 00 00 00 00 00 00 00 00 00 00 00 02>
INFO[client.js]: -  <Buffer 93 05 c0 02>
INFO[client.js]: -  <Buffer 93 01 c0 04>
byte stream connect attempt 0
INFO[client.js]: -  <Buffer 93 02 da 00 24 00 00 00 40 00 00 80 3f 00 00 ca 42 00 00 00 00 00 00 80 3f 00 00 40 40 00 00 00 00 00 00 00 00 00 00 00 00 04>
INFO[client.js]: -  <Buffer 93 05 c0 04>
INFO[client.js]: -  <Buffer 93 01 c0 06>
byte stream connect attempt 0
INFO[client.js]: -  <Buffer 93 02 da 00 24 00 00 00 40 00 00 80 3f 00 00 ca 42 00 00 00 00 00 00 80 3f 00 00 40 40 00 00 00 00 00 00 00 00 00 00 00 00 06>
INFO[client.js]: -  <Buffer 93 05 c0 06>
INFO[client.js]: -  <Buffer 93 01 c0 08>
byte stream connect attempt 0
INFO[client.js]: -  <Buffer 93 02 da 00 24 00 00 00 40 00 00 80 3f 00 00 ce 42 00 00 00 00 00 00 80 3f 00 00 40 40 00 00 00 00 00 00 00 00 00 00 00 00 08>
INFO[client.js]: -  <Buffer 93 05 c0 08>
INFO[client.js]: -  <Buffer 93 01 c0 0a>
byte stream connect attempt 0
INFO[client.js]: -  <Buffer 93 02 da 00 24 00 00 00 40 00 00 80 3f 00 00 c6 42 00 00 00 00 00 00 80 3f 00 00 40 40 00 00 00 00 00 00 00 00 00 00 00 00 0a>
INFO[client.js]: -  <Buffer 93 05 c0 0a>
```

점점 증가함 

에러가 발생할때는 해당 부분 실행도 하지 않음

**Comment by Francis0121** [comment]
아래 부분 수정( https://github.com/einaros/ws/issues/283 참고 )
`/home/russa/git/vrcs/web/vrcs/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:223`

``` javascript
Receiver.prototype.endPacket = function() {
  if (this.dead) return;
```

**Comment by Francis0121** [comment]
위의 부분 처럼 하면 실행은 되지만 아래의 다른 에러 발생.
![image](https://cloud.githubusercontent.com/assets/3794501/5570515/0996a466-8fc6-11e4-8e43-95e5bcfe8cec.png)

```
INFO[client.js]: -  2probe

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Received unparsable message: TypeError: Object 2probe has no method 'readUInt8'
    at /home/russa/git/vrcs/web/vrcs/node_modules/binaryjs/lib/client.js:101:37
    at process._tickCallback (node.js:419:13)
```

**Comment by Francis0121** [comment]
https://github.com/Automattic/socket.io/issues/1824

https://github.com/Automattic/socket.io-client/issues/737

**Comment by Francis0121** [comment]
결국 오류의 발생 지점은
Socket.io 와 Binaryjs 의 socket이 같은 port를 사용하게 되면서 
socket.io의 통신이 binaryjs에 전달되게 되면서 문제가 생겼던것으로 판단된다.

따라서 두개의 port를 다른것으로 사용하면서 이를 해결하였다

``` javascript
// server
var BinaryServer = require('binaryjs').BinaryServer; // BinaryJs (Byte stream)
var bs = BinaryServer({port : 9000}); // Start BinaryJs server
var io = require('socket.io').listen(server); // Socket.io
```

``` javascript
// client
var client = new BinaryClient('ws://localhost:9000'); // Byte streaming

    var clientSend = function(){
        client.send(makeBuffer());
    };

```
